// <auto-generated />
using System;
using EducationApp.Data.Concrete.EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationApp.Data.Migrations
{
    [DbContext(typeof(EducationAppContext))]
    partial class EducationAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("EducationApp.Entity.Concrete.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 977, DateTimeKind.Local).AddTicks(9614),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 977, DateTimeKind.Local).AddTicks(9634),
                            UserId = "300b6f1f-4e38-4bec-87b2-f3debcc2b62f"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 977, DateTimeKind.Local).AddTicks(9641),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 977, DateTimeKind.Local).AddTicks(9641),
                            UserId = "20aacc70-f2b6-4393-a1c0-0e4b350ab564"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7180),
                            Description = "Yazılım geliştirme, bilgisayar programlarının tasarımı, oluşturulması ve sürdürülmesi sürecidir. Bu süreç, kullanıcı ihtiyaçlarını karşılamak, işlevsellik sağlamak ve teknolojik çözümler üretmek için kodlama, test etme ve dağıtma adımlarını içerir. Yazılım geliştirme, bilgisayar, mobil cihazlar, web uygulamaları, oyunlar ve daha fazlası gibi çeşitli alanlarda kullanılır. Bu süreçte programlama dilleri, veritabanları, algoritmalar ve yazılım tasarım prensipleri gibi araçlar kullanılır. Yazılım geliştirme, hızlı teknolojik ilerlemelerle birlikte sürekli evrilen ve iyileşen bir disiplindir ve kullanıcıların ihtiyaçlarını karşılamak için yenilikçi ve güvenilir çözümler sunmayı hedefler.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7187),
                            Name = "Yazılım Geliştime",
                            Url = "yazilim-gelistirme"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7192),
                            Description = "Mobil uygulama geliştirme, mobil platformlarda çalışabilen kullanışlı ve etkileşimli yazılım uygulamalarının tasarımı, oluşturulması ve dağıtılması sürecidir. Bu süreç, kullanıcı ihtiyaçlarını karşılamak, sorunlara çözüm sunmak ve kullanıcı deneyimini geliştirmek için programlama, arayüz tasarımı, test etme ve dağıtma adımlarını içerir. Mobil uygulama geliştiricileri, Android veya iOS gibi belirli platformlar için uygun programlama dilleri ve geliştirme araçları kullanır. Bu süreç, hızlı teknolojik değişimlerle birlikte sürekli gelişir ve kullanıcıların günlük yaşamlarını kolaylaştıran, eğlence sunan ve işlevsellik sağlayan yenilikçi uygulamaların ortaya çıkmasını sağlar. Mobil uygulama geliştirme, geniş bir kullanıcı tabanına erişmek ve büyüyen mobil pazarlardan yararlanmak isteyen işletmeler ve geliştiriciler için önemli bir stratejidir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7192),
                            Name = "Mobil Uygulama Geliştirme",
                            Url = "mobil-uygulama-gelistirme"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7195),
                            Description = "Oyun geliştirme, video oyunlarının tasarımı, programlaması ve oluşturulması sürecidir. Bu süreç, oyun kavramının belirlenmesi, hikaye yazımı, karakter tasarımı, dünya oluşturma, grafik ve ses tasarımı, oyun mekaniği ve kullanıcı arayüzü gibi aşamaları içerir. Oyun geliştirme ekipleri, oyun programcıları, sanatçılar, tasarımcılar ve ses mühendisleri gibi farklı disiplinlerden profesyonelleri içerir. Geliştiriciler, oyun motorları, programlama dilleri, grafik araçları ve geliştirme ortamları kullanarak oyunun yapısını oluştururlar. Oyun geliştirme, eğlence endüstrisinde önemli bir rol oynar ve oyunculara heyecan verici deneyimler sunmak için sürekli yenilikçilik ve yaratıcılık gerektirir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7195),
                            Name = "Oyun Geliştime",
                            Url = "oyun-gelistirme"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7197),
                            Description = "Web, dünya genelinde bilgilere erişim sağlayan ve kullanıcıların çeşitli hizmetlere bağlanmasını mümkün kılan bir ağdır. Web, HTML, CSS ve JavaScript gibi teknolojilerle oluşturulan web siteleri ve web uygulamaları aracılığıyla çalışır. Web, kullanıcıların arama yapma, e-posta gönderme, sosyal ağlarda etkileşimde bulunma, alışveriş yapma ve daha birçok işlemi gerçekleştirebilecekleri bir platform sunar. Web geliştirme, web sitelerinin ve uygulamalarının tasarımını, kodlamasını, testini ve dağıtımını içerir. Bu süreçte kullanıcı deneyimi, güvenlik, performans ve uyumluluk önemlidir. Web, küresel bağlantıyı sağlayan ve bilgiye kolay erişimi temsil eden önemli bir iletişim ve etkileşim aracıdır.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7197),
                            Name = "Web",
                            Url = "web"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7199),
                            Description = "Veritabanı, yapılandırılmış verilerin depolandığı ve yönetildiği bir elektronik sistemdir. Veritabanları, bilgiyi organize etmek, erişmek, güncellemek ve analiz etmek için kullanılır. İşletmeler, kuruluşlar ve web uygulamaları gibi birçok alan veritabanlarını kullanır. Veritabanı yönetim sistemleri (DBMS), veritabanının oluşturulması, yapılandırılması, sorgulanması ve güncellenmesi için gereken araçları sağlar. Veritabanı tasarımı, veri bütünlüğü, performans optimizasyonu ve güvenlik gibi konular önemlidir. Veritabanları, büyük veri kümelerini işlemek, veri analizi yapmak ve karar verme süreçlerini desteklemek için önemli bir rol oynar. Veritabanları, verilerin etkili bir şekilde yönetilmesini ve bilgi tabanlı çözümler sunulmasını sağlar.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7199),
                            Name = "Veritabanı",
                            Url = "veritabani"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7200),
                            Description = "DevOps, yazılım geliştirme ve işletim süreçlerini birleştirerek, yazılım projelerinin daha hızlı, güvenilir ve sürekli bir şekilde dağıtılmasını sağlayan bir yaklaşımdır. Bu metodoloji, geliştirme (Development) ve işletim (Operations) ekipleri arasında işbirliği ve iletişimi teşvik eder. DevOps, otomasyon, sürekli entegrasyon ve sürekli dağıtım gibi pratikleri kullanarak, yazılımın yaşam döngüsünü hızlandırır ve kaliteyi artırır. Ayrıca, altyapı yönetimi, hata izleme ve performans analizi gibi operasyonel süreçlere odaklanır. DevOps, esneklik, hızlı yanıt verme ve müşteri memnuniyetini artırma gibi faydalar sağlayarak yazılım projelerinin başarısını destekler.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7201),
                            Name = "DevOps",
                            Url = "devops"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7202),
                            Description = "Bulut, internet üzerinde sunulan paylaşımlı bilgi işlem kaynaklarını ifade eder. Bulut hizmetleri, sunucular, depolama, veritabanları, ağ altyapısı ve uygulama hizmetleri gibi kaynaklara erişimi kolaylaştırır. Kullanıcılar, istedikleri zaman istedikleri yerden bu kaynaklara güvenli bir şekilde erişebilir ve ihtiyaçlarına göre ölçeklendirebilir. Bulut hizmetleri, esneklik, ölçeklenebilirlik, veri yedekleme, sürekli çalışma ve maliyet verimliliği gibi avantajlar sağlar. Bulut, işletmeler için altyapı maliyetlerini azaltırken, geliştiriciler için hızlı bir şekilde uygulama dağıtma imkanı sunar. Ayrıca, kullanıcılara mobil cihazlar ve web tarayıcıları aracılığıyla geniş bir hizmet yelpazesine erişme kolaylığı sağlar.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 978, DateTimeKind.Local).AddTicks(7203),
                            Name = "Bulut",
                            Url = "bulut"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1990,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(808),
                            FirstName = "Dominic",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Harmon",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(812),
                            PhotoUrl = "1.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1990,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(817),
                            FirstName = "Justina",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Burch",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(817),
                            PhotoUrl = "1.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1985,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(820),
                            FirstName = "Madison",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Beard",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(821),
                            PhotoUrl = "1.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(823),
                            FirstName = "Sara",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Wade",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(823),
                            PhotoUrl = "1.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1988,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(825),
                            FirstName = "Jacob",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hunt",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(826),
                            PhotoUrl = "1.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1989,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(828),
                            FirstName = "Osamu",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dazai",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(847),
                            PhotoUrl = "1.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1983,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(861),
                            FirstName = "Zachery",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Salas",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(862),
                            PhotoUrl = "1.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(864),
                            FirstName = "Matt",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Haig",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(864),
                            PhotoUrl = "1.png",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(866),
                            FirstName = "William",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hawkingan",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(867),
                            PhotoUrl = "1.png",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1990,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(869),
                            FirstName = "Geraldine",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Richmond",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(869),
                            PhotoUrl = "1.png",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1983,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(871),
                            FirstName = "Steffan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ros",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(872),
                            PhotoUrl = "1.png",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1991,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(873),
                            FirstName = "Nichole",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Talley",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(874),
                            PhotoUrl = "1.png",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1979,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(876),
                            FirstName = "Yetta",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sheppard",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(876),
                            PhotoUrl = "1.png",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1978,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(878),
                            FirstName = "Elijah",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Farley",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(879),
                            PhotoUrl = "1.png",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır. Programlama dillerinin temel yapılarını öğreterek öğrencilerin mantıklı çözümler üretmelerine yardımcı olur. Nesne yönelimli programlama (OOP), veritabanı yönetimi, web ve mobil uygulama geliştirme gibi konulara odaklanabilir. Algoritma ve veri yapıları öğreterek analitik düşünme yeteneğini güçlendirir. Yazılım mühendisliği prensiplerini aktarırken, test ve hata ayıklama tekniklerini de vurgular. Proje tabanlı çalışmalarla pratik deneyim sağlayarak öğrencilerin gerçek dünya projelerinde başarılı olmalarını hedefler. Sürekli güncellenen teknolojilere uyum sağlayarak sektörde rekabetçi bireyler yetiştirir.",
                            BirthOfYear = 1991,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(881),
                            FirstName = "Neil",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Wooten",
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 979, DateTimeKind.Local).AddTicks(881),
                            PhotoUrl = "1.png",
                            ProductId = 15
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7030),
                            Description = "test.",
                            ImageUrl = "1.jpg",
                            InstructorId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7038),
                            Name = ".NET (.NET Core, MVC, Web API)",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7046),
                            Url = ".net-core-mvc"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7049),
                            Description = "testtt.",
                            ImageUrl = "2.jpg",
                            InstructorId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7049),
                            Name = "Java (Spring, Java SE, Java EE)",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7052),
                            Url = "java"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7095),
                            Description = "test.",
                            ImageUrl = "3.png",
                            InstructorId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7097),
                            Name = "Python",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7099),
                            Url = "python"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7100),
                            Description = "test.",
                            ImageUrl = "4.jpeg",
                            InstructorId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7101),
                            Name = "JavaScript",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7103),
                            Url = "javascript"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7104),
                            Description = "test.",
                            ImageUrl = "5.jpg",
                            InstructorId = 5,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7105),
                            Name = "C/C++",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7107),
                            Url = "c/c++	"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7108),
                            Description = "testtt.",
                            ImageUrl = "6.png",
                            InstructorId = 6,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7109),
                            Name = "iOS & Android",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7110),
                            Url = "ios-android"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7111),
                            Description = "test.",
                            ImageUrl = "7.png",
                            InstructorId = 7,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7112),
                            Name = "React Native",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7114),
                            Url = "react-native"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7116),
                            Description = "test.",
                            ImageUrl = "8.png",
                            InstructorId = 8,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7117),
                            Name = "Flutter",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7119),
                            Url = "flutter"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7120),
                            Description = "test.",
                            ImageUrl = "9.jpg",
                            InstructorId = 9,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7120),
                            Name = "Ionic",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7122),
                            Url = "ionic"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7123),
                            Description = "test.",
                            ImageUrl = "10.jpeg",
                            InstructorId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7124),
                            Name = "Unity",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7126),
                            Url = "unity"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7127),
                            Description = "test.",
                            ImageUrl = "11.png",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7127),
                            Name = "Unreal Engine",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7129),
                            Url = "unreal-engine"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7130),
                            Description = "testtt.",
                            ImageUrl = "12.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7131),
                            Name = "GameMaker Studio",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7132),
                            Url = "gamemaker-studio"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7133),
                            Description = "test.",
                            ImageUrl = "13.jpeg",
                            InstructorId = 13,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7134),
                            Name = "Buildbox",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7136),
                            Url = "buildbox"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7137),
                            Description = "test.",
                            ImageUrl = "14.png",
                            InstructorId = 14,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7137),
                            Name = "PHP",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7139),
                            Url = "php"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7140),
                            Description = "test.",
                            ImageUrl = "15.jpeg",
                            InstructorId = 8,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7140),
                            Name = "React",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7142),
                            Url = "react"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7143),
                            Description = "test.",
                            ImageUrl = "16.png",
                            InstructorId = 9,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7144),
                            Name = "Angular",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7146),
                            Url = "angular"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7147),
                            Description = "test.",
                            ImageUrl = "17.png",
                            InstructorId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7147),
                            Name = "Node.js",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7149),
                            Url = "nodejs"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7150),
                            Description = "test.",
                            ImageUrl = "18.jpg",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7151),
                            Name = "Microsoft SQL Server",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7152),
                            Url = "microsoft-sql-server"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7155),
                            Description = "testtt.",
                            ImageUrl = "19.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7155),
                            Name = "MySQL",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7157),
                            Url = "mysql"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7158),
                            Description = "test.",
                            ImageUrl = "20.png",
                            InstructorId = 13,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7159),
                            Name = "PostgreSQL",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7160),
                            Url = "postgresql"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7162),
                            Description = "test.",
                            ImageUrl = "21.png",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7162),
                            Name = "SQLite",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7164),
                            Url = "sqlite"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7165),
                            Description = "testtt.",
                            ImageUrl = "22.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7165),
                            Name = "Oracle",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7167),
                            Url = "oracle"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7168),
                            Description = "test.",
                            ImageUrl = "23.png",
                            InstructorId = 13,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7169),
                            Name = "Docker",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7170),
                            Url = "docker"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7172),
                            Description = "test.",
                            ImageUrl = "24.png",
                            InstructorId = 14,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7172),
                            Name = "Jenkins",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7174),
                            Url = "jenkins"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7175),
                            Description = "test.",
                            ImageUrl = "25.png",
                            InstructorId = 8,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7175),
                            Name = "Ansible",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7177),
                            Url = "ansible"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7178),
                            Description = "test.",
                            ImageUrl = "26.jpeg",
                            InstructorId = 9,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7179),
                            Name = "Sonarcube",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7180),
                            Url = "sonarcube"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7182),
                            Description = "test.",
                            ImageUrl = "27.png",
                            InstructorId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7182),
                            Name = "AWS",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7184),
                            Url = "aws"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7185),
                            Description = "test.",
                            ImageUrl = "28.png",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7186),
                            Name = "Azure",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7187),
                            Url = "azure"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7188),
                            Description = "testtt.",
                            ImageUrl = "29.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7189),
                            Name = "Serverless",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7191),
                            Url = "serverless"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7192),
                            Description = "testtt.",
                            ImageUrl = "30.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7192),
                            Name = "Cloud Storage",
                            Price = 100m,
                            Time = new DateTime(2023, 7, 28, 1, 46, 45, 981, DateTimeKind.Local).AddTicks(7199),
                            Url = "cloudstorage"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 7
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9836982d-6c1c-4e33-8a90-03f70b029031",
                            Description = "Yöneticilerin rolü bu.",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0fb7a860-63ec-478a-bc1d-ac9857a16ce6",
                            Description = "Diğer tüm kullanıcıların rolü bu.",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "300b6f1f-4e38-4bec-87b2-f3debcc2b62f",
                            AccessFailedCount = 0,
                            Address = "Kemalpaşa Mh. Zühtübey Sk. No:12 D:3 Üsküdar",
                            City = "İstanbul",
                            ConcurrencyStamp = "7203d510-8ba0-4711-8c49-00e31b0bf02f",
                            DateOfBirth = new DateTime(1985, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "denizfoca@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Deniz",
                            Gender = "Kadın",
                            LastName = "Foça",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "DENIZFOCA@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJAbJc6ptm2SU01S7v9TFKWNaaT6/HaBukgWctd/KvT4reVumQP9lSeMQUWiFSsP3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "20aacc70-f2b6-4393-a1c0-0e4b350ab564",
                            AccessFailedCount = 0,
                            Address = "Barbaros Bulvarı Feda İş Hanı K:5 D:23 Beşiktaş",
                            City = "İstanbul",
                            ConcurrencyStamp = "6d950686-5468-4ec1-bc69-13a4c39bf9bf",
                            DateOfBirth = new DateTime(1983, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "muratkendirli@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Murat",
                            Gender = "Erkek",
                            LastName = "Kendirli",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "MURATKENDIRLI@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEGiqbk/yV0JHYuW+KS9Ft4dZ0iP6mGx2ehb8rKSKYeuqevB2mTPi+YHOufr3WEo0Cw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "300b6f1f-4e38-4bec-87b2-f3debcc2b62f",
                            RoleId = "9836982d-6c1c-4e33-8a90-03f70b029031"
                        },
                        new
                        {
                            UserId = "20aacc70-f2b6-4393-a1c0-0e4b350ab564",
                            RoleId = "0fb7a860-63ec-478a-bc1d-ac9857a16ce6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Cart", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.CartItem", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Instructor", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Order", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.OrderItem", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Product", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Instructor", "Instructor")
                        .WithMany("Products")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.ProductCategory", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Instructor", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
